server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
        #配置git仓库的地址
          uri: https://gitee.com/pleiyang/springcloudconfig
          username: pleiyang
          password: mygitee1218
#logging:
#  level:
#    org.springframework.cloud: debug
#    org.springframework.boot: debug