server:
  port: 8010

spring:
    application:
      #注册到eureka server 上的应用名称
      name: microservice-consumer-user


eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    #将自己的ip注册到额ureka server
    prefer-ip-address: true