server:
  port: 8020

spring:
    application:
      #注册到eureka server 上的应用名称
      name: microservice-consumer-user,microservice-consumer-novie-fegin-hystrix-fallback-stream


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    #将自己的ip注册到额ureka server
    prefer-ip-address: true