server:
  port: 8010

spring:
    application:
      #注册到eureka server 上的应用名称
      name: microservice-consumer-user


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    #将自己的ip注册到额ureka server
    prefer-ip-address: true
logging:
  level:
    com.plerer.controller.UserFeignClient: DEBUG # 将Feign接口的日志级别设置成DEBUG，因为Feign的Logger.Level只对DEBUG作出响应。
