server:
  port: 8761

eureka:
  client:
    #是否将自己注册到eurekaServer
    registerWithEureka: false
    #是否从eurekaServer 获取注册信息
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:

  basic:
    enabled: true               # 开启基于HTTP basic的认证
  user:
    name: user                  # 配置登录的账号是user
    password: password123       # 配置登录的密码是password123